spec:
  ports:
  - appProtocol: http
    name: http
    nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    nodePort: 30443
    port: 8443
    protocol: TCP
    targetPort: https