kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        authorization-mode: "AlwaysAllow"
  extraPortMappings:
  - containerPort: 30080  # nodePort of the service running in the cluster
    hostPort: 8080        # port on my laptop
    protocol: TCP
  - containerPort: 30443
    hostPort: 8443
    protocol: TCP