apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ispy
  name: ispy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ispy
  strategy: {}
  template:
    metadata:
      labels:
        app: ispy
    spec:
      containers:
        - image: "{{ .Values.image }}:{{ .Values.tag }}"
          name: ispy
          resources:
            requests:
              cpu: 32m
              memory: 32Mi
            limits:
              cpu: 500m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
