apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ispy
spec:
  parentRefs:
  - name: cafe-gateway
    namespace: istio-system
    sectionName: https-ispy 
  rules:
  - backendRefs:
    - name: ispy
      weight: 1
      port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ispy-http-redirect
spec:
  parentRefs:
  - name: cafe-gateway
    namespace: istio-system
    sectionName: http-ispy     
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
