apiVersion: v1
kind: Service
metadata:
  labels:
    app: ispy
  name: ispy
spec:
  ports:
  - name: http
    nodePort: 31080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ispy
  type: NodePort

